# Generated by Django 5.0.1 on 2024-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('search_area', models.TextField()),
                ('funding_source', models.TextField()),
                ('budget', models.IntegerField()),
                ('discription', models.TextField()),
                ('publication', models.TextField()),
                ('keywords', models.TextField()),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('InProgress', 'InProgress'), ('Done', 'Done')], default='ToDo', max_length=10)),
                ('website', models.TextField()),
                ('related_research', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='researcher_type',
        ),
        migrations.CreateModel(
            name='Labratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipments', models.TextField()),
                ('capacity', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('managers', models.ManyToManyField(to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capcity', models.IntegerField()),
                ('books', models.IntegerField()),
                ('managers', models.ManyToManyField(to='api.employee')),
            ],
        ),
    ]
