# Generated by Django 5.0.1 on 2024-01-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_research_remove_researcher_researcher_type_labratory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Satureday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.research')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.researcher')),
            ],
        ),
        migrations.AddField(
            model_name='labratory',
            name='schedules',
            field=models.ManyToManyField(to='api.schedule'),
        ),
        migrations.AddField(
            model_name='library',
            name='schedules',
            field=models.ManyToManyField(to='api.schedule'),
        ),
    ]
