# Generated by Django 4.2 on 2024-02-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_meeting', '0001_initial'),
        ('personels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelsmeeting',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_meetings', to='personels.personel'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='establisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_owner', to='personels.personel'),
        ),
    ]
