# Generated by Django 4.2 on 2024-01-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personels', '0002_performancereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='personels.personel'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviewer', to='personels.personel'),
        ),
    ]
