# Generated by Django 4.2 on 2024-01-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personelcourse',
            options={'verbose_name': 'personel course', 'verbose_name_plural': 'personel courses'},
        ),
    ]