FROM node:lts-slim

WORKDIR /app/

ENV PNPM_HOME "/pnpm"
ENV PATH "$PNPM_HOME:$PATH"
RUN corepack enable

ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
RUN pnpm install

COPY . ./