router.register(r"Researcher", views.ResearcherViewSet)
router.register(r"Research", views.ResearchViewSet)
router.register(r"ResearchMember", views.ResearchMemberViewSet)
router.register(r"Schedule", views.ScheduleViewSet)
router.register(r"Laboratory", views.LaboratoryViewSet)
router.register(r"Library", views.LibraryViewSet)