# Generated by Django 4.2 on 2024-02-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='personels.personel'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviewer', to='personels.personel'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='personels.personel'),
        ),
    ]
