# Generated by Django 4.2 on 2024-01-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personels', '0003_alter_performancereview_personel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personels', to='personels.position'),
        ),
    ]