# Generated by Django 4.2 on 2024-01-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personels', '0004_alter_personel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personels', to='personels.position'),
        ),
    ]
